##############################################################################
# Copyright (c) 2017 HUAWEI TECHNOLOGIES CO.,LTD and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

common_config:
  log_dir: '/tmp/'
  rc_dir: '/tmp/admin_rc.sh'
  pod_info: '/tmp/pod.yaml'
  yardstick_rc_dir: '/etc/yardstick/openstack.creds'
  releng_dir: '/home/opnfv/releng'
  fetch_os_file: 'utils/fetch_os_creds.sh'
  yardstick_image_dir: '/tmp/yardstick.img'
  image_url: 'http://artifacts.opnfv.org/yardstick/images/yardstick-nsb-image.img'
  yardstick_image_name: 'bottlenecks_yardstick'
